# Generated by Django 5.1.1 on 2026-06-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descriptiom',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='your description'),
        ),
    ]
